//
// Created by 曾辉 on 2019-06-13.
//

#ifndef NDK_DAY03_DZCONSTDEFINE_H
#define NDK_DAY03_DZCONSTDEFINE_H

#define FIND_AUDIO_STREAM_ERROR_CODE -0x011
#define FIND_AUDIO_DECODER_ERROR_CODE -0x012
#define FIND_VIDEO_STREAM_ERROR_CODE -0x013
#define SWS_GET_CONTEXT_ERROR_CODE -0x014

#endif //NDK_DAY03_DZCONSTDEFINE_H
